# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Hamel Inspections LLC
email: hamelinspections@gmail.com
author: Edward Hamel
description: Home inspections to give you the confidence to make informed decisions when purchasing your new home. Our focus is on complete, understandable, and thorough reports.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: github
    #url: https://github.com/IronSummitMedia/startbootstrap
 # - title: linkedin
    #url: 
